# Databases

# MySQL
mysql:
  host: 127.0.0.1
  port: 3306
  database: minecraft
  password: 1234
  username: admin
# SQLite
sqlite:
  file_name: smp

database_type: mysql

# Discord Webhooks
enable_discord_webhook: false
webhook: 

# Breading Chances (default: 40%)
mobBreedingSuccessPercentage: 40